#spring.datasource.url=jdbc:mysql://localhost:3306/monitor
#spring.datasource.username=root
#spring.datasource.password=956788752
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#
#spring.jpa.properties.hibernate.hbm2ddl.auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.show-sql= true


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/educationsystem?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false

    username: root
    password: 956788752
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  thymeleaf:
    cache: false



server:
  port: 8888



